steps:
  # Build the container image with secrets from Secret Manager
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker build --build-arg=API_KEY=$$GEMINI_API_KEY --build-arg=FIREBASE_API_KEY=$$FIREBASE_API_KEY --build-arg=FIREBASE_AUTH_DOMAIN=$$FIREBASE_AUTH_DOMAIN --build-arg=FIREBASE_PROJECT_ID=$$FIREBASE_PROJECT_ID --build-arg=FIREBASE_STORAGE_BUCKET=$$FIREBASE_STORAGE_BUCKET --build-arg=FIREBASE_MESSAGING_SENDER_ID=$$FIREBASE_MESSAGING_SENDER_ID --build-arg=FIREBASE_APP_ID=$$FIREBASE_APP_ID -t gcr.io/$PROJECT_ID/we-accounting-ai:$COMMIT_SHA -t gcr.io/$PROJECT_ID/we-accounting-ai:latest .'
    secretEnv:
      - 'GEMINI_API_KEY'
      - 'FIREBASE_API_KEY'
      - 'FIREBASE_AUTH_DOMAIN'
      - 'FIREBASE_PROJECT_ID'
      - 'FIREBASE_STORAGE_BUCKET'
      - 'FIREBASE_MESSAGING_SENDER_ID'
      - 'FIREBASE_APP_ID'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/we-accounting-ai']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'we-accounting-ai'
      - '--image=gcr.io/$PROJECT_ID/we-accounting-ai:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'

# Secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
      env: 'GEMINI_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_API_KEY/versions/latest
      env: 'FIREBASE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'FIREBASE_AUTH_DOMAIN'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_PROJECT_ID/versions/latest
      env: 'FIREBASE_PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'FIREBASE_STORAGE_BUCKET'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_APP_ID/versions/latest
      env: 'FIREBASE_APP_ID'

substitutions:
  _REGION: asia-southeast1

images:
  - 'gcr.io/$PROJECT_ID/we-accounting-ai:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/we-accounting-ai:latest'

options:
  logging: CLOUD_LOGGING_ONLY
