/**
 * Accounting Task Sync Service
 * 
 * เชื่อมสถานะงานบัญชีกับ Task Management
 * - สร้าง Task อัตโนมัติจาก Document, Bank Statement, Closing
 * - อัพเดท Task Status เมื่อ workflow เปลี่ยน
 * - แจ้งเตือนเมื่อมีงานใหม่หรือ deadline ใกล้
 */

import { Task, TaskCategory, TaskStatus, TaskPriority, TaskTemplate } from '../types/tasks';
import { Client, DocumentRecord, PostedGLEntry, BankTransaction } from '../types';
import { MonthlyClosingProgress } from './accountingFirmEngine';
import { databaseService } from './database';
import taskManagement from './taskManagement';

// ============================================================================
// TYPES
// ============================================================================

export interface AccountingTask extends Task {
    accountingContext: {
        type: 'document' | 'reconciliation' | 'closing' | 'tax' | 'report';
        sourceId?: string;          // Document ID, Transaction ID, etc.
        clientId: string;
        period?: string;            // YYYY-MM
        deadline?: string;
        isAutoGenerated: boolean;
        workflowStatus?: string;
        linkedItems?: string[];
    };
}

export interface TaskSyncEvent {
    type: 'document_uploaded' | 'document_approved' | 'reconciliation_complete' |
    'closing_started' | 'closing_complete' | 'tax_due' | 'report_generated';
    payload: any;
    timestamp: string;
}

// ============================================================================
// TASK TEMPLATES FOR ACCOUNTING
// ============================================================================

export const ACCOUNTING_TASK_TEMPLATES: Record<string, Partial<TaskTemplate>> = {
    // Document Processing
    document_review: {
        name: 'ตรวจสอบเอกสาร',
        category: 'document_review',
        estimatedHours: 0.5,
        defaultTitle: 'ตรวจสอบเอกสาร',
        defaultChecklist: [
            { id: 'check1', text: 'ตรวจสอบความถูกต้องของข้อมูล', completed: false },
            { id: 'check2', text: 'ตรวจสอบรหัสบัญชี', completed: false },
            { id: 'check3', text: 'ตรวจสอบภาษี VAT/WHT', completed: false },
            { id: 'check4', text: 'อนุมัติหรือแก้ไข', completed: false }
        ]
    },

    gl_posting: {
        name: 'ลงบัญชี',
        category: 'gl_posting',
        estimatedHours: 0.25,
        defaultTitle: 'ลงบัญชีจากเอกสาร',
        defaultChecklist: [
            { id: 'check1', text: 'ตรวจสอบรายการบันทึกบัญชี', completed: false },
            { id: 'check2', text: 'ยืนยันยอดเดบิต/เครดิต', completed: false },
            { id: 'check3', text: 'Post รายการ', completed: false }
        ]
    },

    // Bank Reconciliation
    bank_reconciliation: {
        name: 'กระทบยอดธนาคาร',
        category: 'bank_reconciliation',
        estimatedHours: 2,
        defaultTitle: 'กระทบยอดธนาคาร',
        defaultChecklist: [
            { id: 'check1', text: 'นำเข้า Bank Statement', completed: false },
            { id: 'check2', text: 'Match รายการอัตโนมัติ', completed: false },
            { id: 'check3', text: 'ตรวจสอบรายการ Unmatched', completed: false },
            { id: 'check4', text: 'Match รายการด้วยมือ', completed: false },
            { id: 'check5', text: 'สรุปผลกระทบยอด', completed: false }
        ]
    },

    // Period Closing
    period_closing: {
        name: 'ปิดบัญชีประจำเดือน',
        category: 'period_closing',
        estimatedHours: 4,
        defaultTitle: 'ปิดบัญชีเดือน',
        defaultChecklist: [
            { id: 'check1', text: 'ตรวจสอบเอกสารครบถ้วน', completed: false },
            { id: 'check2', text: 'กระทบยอดธนาคารเสร็จ', completed: false },
            { id: 'check3', text: 'คำนวณค่าเสื่อมราคา', completed: false },
            { id: 'check4', text: 'บันทึกค่าใช้จ่ายค้างจ่าย', completed: false },
            { id: 'check5', text: 'ตรวจสอบงบทดลอง', completed: false },
            { id: 'check6', text: 'ปิดบัญชี P&L', completed: false },
            { id: 'check7', text: 'ล็อคงวดบัญชี', completed: false }
        ]
    },

    // Tax Filing
    vat_filing: {
        name: 'ยื่น ภ.พ.30',
        category: 'tax_filing',
        estimatedHours: 1,
        defaultTitle: 'ยื่นแบบ ภ.พ.30',
        defaultChecklist: [
            { id: 'check1', text: 'รวบรวมใบกำกับภาษีซื้อ-ขาย', completed: false },
            { id: 'check2', text: 'ตรวจสอบยอดภาษีซื้อ-ขาย', completed: false },
            { id: 'check3', text: 'สร้างแบบ ภ.พ.30', completed: false },
            { id: 'check4', text: 'ตรวจสอบความถูกต้อง', completed: false },
            { id: 'check5', text: 'ยื่นแบบ', completed: false }
        ]
    },

    wht_filing: {
        name: 'ยื่น ภ.ง.ด.3/53',
        category: 'tax_filing',
        estimatedHours: 1.5,
        defaultTitle: 'ยื่นแบบ ภ.ง.ด.3/53',
        defaultChecklist: [
            { id: 'check1', text: 'รวบรวมรายการหักภาษี ณ ที่จ่าย', completed: false },
            { id: 'check2', text: 'สร้างหนังสือรับรอง 50 ทวิ', completed: false },
            { id: 'check3', text: 'ตรวจสอบความถูกต้อง', completed: false },
            { id: 'check4', text: 'ยื่นแบบ', completed: false }
        ]
    },

    // Financial Report
    financial_report: {
        name: 'จัดทำงบการเงิน',
        category: 'financial_report',
        estimatedHours: 3,
        defaultTitle: 'จัดทำงบการเงิน',
        defaultChecklist: [
            { id: 'check1', text: 'สร้างงบทดลอง', completed: false },
            { id: 'check2', text: 'สร้างงบกำไรขาดทุน', completed: false },
            { id: 'check3', text: 'สร้างงบแสดงฐานะการเงิน', completed: false },
            { id: 'check4', text: 'ตรวจสอบความถูกต้อง', completed: false },
            { id: 'check5', text: 'ส่งให้ลูกค้าตรวจสอบ', completed: false }
        ]
    }
};

// ============================================================================
// TAX DEADLINES (Thai Revenue Department)
// ============================================================================

export const TAX_DEADLINES = {
    PP30_VAT: 15,           // วันที่ 15 ของเดือนถัดไป
    PND3_INDIVIDUAL: 7,     // วันที่ 7 ของเดือนถัดไป
    PND53_COMPANY: 7,       // วันที่ 7 ของเดือนถัดไป
    PND1_SALARY: 7,         // วันที่ 7 ของเดือนถัดไป
    SOCIAL_SECURITY: 15,    // วันที่ 15 ของเดือนถัดไป
};

// ============================================================================
// SYNC SERVICE CLASS
// ============================================================================

class AccountingTaskSyncService {
    private tasks: AccountingTask[] = [];
    private eventLog: TaskSyncEvent[] = [];

    // ==========================================================================
    // DOCUMENT PROCESSING TASKS
    // ==========================================================================

    /**
     * Create task when document is uploaded
     */
    createDocumentReviewTask(
        document: DocumentRecord,
        client: Client,
        assignToStaffId?: string
    ): AccountingTask {
        const template = ACCOUNTING_TASK_TEMPLATES.document_review;
        const now = new Date();

        const task: AccountingTask = {
            id: `TASK-DOC-${document.id}-${Date.now()}`,
            title: `${template?.defaultTitle} - ${document.filename}`,
            description: `ตรวจสอบเอกสาร "${document.filename}" ของลูกค้า ${client.name}`,
            category: 'document_review',
            assignedTo: assignToStaffId || null,
            assignedBy: 'system',
            assignedAt: now.toISOString(),
            priority: this.determinePriority(document),
            dueDate: this.calculateDueDate(1), // 1 day
            status: 'todo',
            progress: 0,
            canBeAutomated: document.ai_data?.confidence_score ? document.ai_data.confidence_score >= 85 : false,
            automationAttempts: 0,
            timeSpent: 0,
            timeEntries: [],
            checklist: (template?.defaultChecklist || []).map(c => ({
                ...c,
                id: `${c.id}-${Date.now()}`
            })),
            comments: [],
            activityLog: [{
                id: `act-${Date.now()}`,
                timestamp: now.toISOString(),
                userId: 'system',
                userName: 'System',
                action: 'created',
                details: 'สร้างงานอัตโนมัติจากเอกสารใหม่'
            }],
            tags: ['auto-generated', 'document'],
            properties: [],
            estimatedHours: template?.estimatedHours || 0.5,
            clientId: client.id,
            clientName: client.name,
            documentIds: [document.id],
            createdAt: now.toISOString(),
            updatedAt: now.toISOString(),
            accountingContext: {
                type: 'document',
                sourceId: document.id,
                clientId: client.id,
                isAutoGenerated: true,
                workflowStatus: document.status,
                linkedItems: [document.id]
            }
        };

        this.tasks.push(task);
        this.logEvent('document_uploaded', { documentId: document.id, taskId: task.id });

        return task;
    }

    /**
     * Update task when document is approved
     */
    onDocumentApproved(documentId: string): AccountingTask | null {
        const task = this.tasks.find(t =>
            t.accountingContext.type === 'document' &&
            t.accountingContext.sourceId === documentId
        );

        if (task) {
            task.status = 'completed';
            task.progress = 100;
            task.completedAt = new Date().toISOString();
            task.accountingContext.workflowStatus = 'approved';

            // Complete all checklist items
            task.checklist.forEach(item => {
                item.completed = true;
                item.completedAt = new Date().toISOString();
            });

            this.logEvent('document_approved', { documentId, taskId: task.id });
        }

        return task || null;
    }

    // ==========================================================================
    // BANK RECONCILIATION TASKS
    // ==========================================================================

    /**
     * Create bank reconciliation task for a client/period
     */
    createReconciliationTask(
        client: Client,
        period: string,
        unmatchedCount: number,
        assignToStaffId?: string
    ): AccountingTask {
        const template = ACCOUNTING_TASK_TEMPLATES.bank_reconciliation;
        const now = new Date();

        const task: AccountingTask = {
            id: `TASK-RECON-${client.id}-${period}-${Date.now()}`,
            title: `${template?.defaultTitle} - ${client.name} (${period})`,
            description: `กระทบยอดธนาคารของ ${client.name} สำหรับเดือน ${period}\nมีรายการที่ยังไม่ match: ${unmatchedCount} รายการ`,
            category: 'bank_reconciliation',
            assignedTo: assignToStaffId || null,
            assignedBy: 'system',
            assignedAt: now.toISOString(),
            priority: unmatchedCount > 10 ? 'high' : 'medium',
            dueDate: this.getEndOfMonth(period),
            status: 'todo',
            progress: 0,
            canBeAutomated: unmatchedCount === 0, // Can auto-complete if all matched
            automationAttempts: 0,
            timeSpent: 0,
            timeEntries: [],
            checklist: (template?.defaultChecklist || []).map(c => ({
                ...c,
                id: `${c.id}-${Date.now()}`
            })),
            comments: [],
            activityLog: [{
                id: `act-${Date.now()}`,
                timestamp: now.toISOString(),
                userId: 'system',
                userName: 'System',
                action: 'created',
                details: `สร้างงานกระทบยอดอัตโนมัติ - ${unmatchedCount} รายการรอ match`
            }],
            tags: ['auto-generated', 'reconciliation', period],
            properties: [],
            estimatedHours: template?.estimatedHours || 2,
            clientId: client.id,
            clientName: client.name,
            createdAt: now.toISOString(),
            updatedAt: now.toISOString(),
            accountingContext: {
                type: 'reconciliation',
                clientId: client.id,
                period,
                isAutoGenerated: true,
                linkedItems: []
            }
        };

        this.tasks.push(task);
        return task;
    }

    // ==========================================================================
    // MONTHLY CLOSING TASKS
    // ==========================================================================

    /**
     * Create monthly closing tasks for a client
     */
    createMonthlyClosingTasks(
        client: Client,
        period: string,
        assignToStaffId?: string
    ): AccountingTask[] {
        const createdTasks: AccountingTask[] = [];
        const now = new Date();
        const [year, month] = period.split('-').map(Number);

        // Main closing task
        const closingTask = this.createClosingTask(client, period, assignToStaffId);
        createdTasks.push(closingTask);

        // VAT Filing task (due 15th of next month)
        const vatDueDate = new Date(year, month, TAX_DEADLINES.PP30_VAT);
        const vatTask = this.createTaxFilingTask(
            client,
            period,
            'vat_filing',
            'ยื่นแบบ ภ.พ.30',
            vatDueDate.toISOString().slice(0, 10),
            assignToStaffId
        );
        createdTasks.push(vatTask);

        // WHT Filing task (due 7th of next month)
        const whtDueDate = new Date(year, month, TAX_DEADLINES.PND3_INDIVIDUAL);
        const whtTask = this.createTaxFilingTask(
            client,
            period,
            'wht_filing',
            'ยื่นแบบ ภ.ง.ด.3/53',
            whtDueDate.toISOString().slice(0, 10),
            assignToStaffId
        );
        createdTasks.push(whtTask);

        return createdTasks;
    }

    private createClosingTask(
        client: Client,
        period: string,
        assignToStaffId?: string
    ): AccountingTask {
        const template = ACCOUNTING_TASK_TEMPLATES.period_closing;
        const now = new Date();

        const task: AccountingTask = {
            id: `TASK-CLOSE-${client.id}-${period}-${Date.now()}`,
            title: `ปิดบัญชีเดือน ${period} - ${client.name}`,
            description: `ปิดบัญชีประจำเดือน ${period} ของลูกค้า ${client.name}`,
            category: 'period_closing',
            assignedTo: assignToStaffId || null,
            assignedBy: 'system',
            assignedAt: now.toISOString(),
            priority: 'high',
            dueDate: this.getEndOfNextMonth(period),
            status: 'todo',
            progress: 0,
            canBeAutomated: false,
            automationAttempts: 0,
            timeSpent: 0,
            timeEntries: [],
            checklist: (template?.defaultChecklist || []).map(c => ({
                ...c,
                id: `${c.id}-${Date.now()}`
            })),
            comments: [],
            activityLog: [{
                id: `act-${Date.now()}`,
                timestamp: now.toISOString(),
                userId: 'system',
                userName: 'System',
                action: 'created',
                details: 'สร้างงานปิดบัญชีอัตโนมัติ'
            }],
            tags: ['auto-generated', 'closing', period],
            properties: [],
            estimatedHours: template?.estimatedHours || 4,
            clientId: client.id,
            clientName: client.name,
            createdAt: now.toISOString(),
            updatedAt: now.toISOString(),
            accountingContext: {
                type: 'closing',
                clientId: client.id,
                period,
                isAutoGenerated: true
            }
        };

        this.tasks.push(task);
        return task;
    }

    private createTaxFilingTask(
        client: Client,
        period: string,
        templateKey: string,
        title: string,
        dueDate: string,
        assignToStaffId?: string
    ): AccountingTask {
        const template = ACCOUNTING_TASK_TEMPLATES[templateKey];
        const now = new Date();

        const task: AccountingTask = {
            id: `TASK-TAX-${templateKey}-${client.id}-${period}-${Date.now()}`,
            title: `${title} - ${client.name} (${period})`,
            description: `${title} ของ ${client.name} สำหรับเดือน ${period}`,
            category: 'tax_filing',
            assignedTo: assignToStaffId || null,
            assignedBy: 'system',
            assignedAt: now.toISOString(),
            priority: 'high',
            dueDate,
            status: 'todo',
            progress: 0,
            canBeAutomated: false,
            automationAttempts: 0,
            timeSpent: 0,
            timeEntries: [],
            checklist: (template?.defaultChecklist || []).map(c => ({
                ...c,
                id: `${c.id}-${Date.now()}`
            })),
            comments: [],
            activityLog: [{
                id: `act-${Date.now()}`,
                timestamp: now.toISOString(),
                userId: 'system',
                userName: 'System',
                action: 'created',
                details: `สร้างงานยื่นภาษีอัตโนมัติ - กำหนดส่ง ${dueDate}`
            }],
            tags: ['auto-generated', 'tax', period],
            properties: [],
            estimatedHours: template?.estimatedHours || 1,
            clientId: client.id,
            clientName: client.name,
            createdAt: now.toISOString(),
            updatedAt: now.toISOString(),
            accountingContext: {
                type: 'tax',
                clientId: client.id,
                period,
                deadline: dueDate,
                isAutoGenerated: true
            }
        };

        this.tasks.push(task);
        return task;
    }

    // ==========================================================================
    // SYNC FROM ACCOUNTING WORKFLOW
    // ==========================================================================

    /**
     * Sync task status from monthly closing progress
     */
    syncFromClosingProgress(
        clientId: string,
        period: string,
        progress: MonthlyClosingProgress
    ): void {
        // Find related closing task
        const closingTask = this.tasks.find(t =>
            t.accountingContext.type === 'closing' &&
            t.accountingContext.clientId === clientId &&
            t.accountingContext.period === period
        );

        if (closingTask) {
            // Update progress based on workflow
            const { phases } = progress;
            let completed = 0;
            let total = closingTask.checklist.length;

            // Map phases to checklist items
            if (phases.documentsProcessed.pending === 0 && phases.documentsProcessed.completed > 0) {
                this.completeChecklistItem(closingTask, 0);
                completed++;
            }
            if (phases.bankReconciled.unmatched === 0 && phases.bankReconciled.matched > 0) {
                this.completeChecklistItem(closingTask, 1);
                completed++;
            }
            if (phases.depreciationCalculated) {
                this.completeChecklistItem(closingTask, 2);
                completed++;
            }
            if (phases.accrualsRecorded) {
                this.completeChecklistItem(closingTask, 3);
                completed++;
            }
            // Check trial balance - if GL is balanced
            if (Math.abs(phases.glPosted.totalDebit - phases.glPosted.totalCredit) < 0.01) {
                this.completeChecklistItem(closingTask, 4);
                completed++;
            }
            if (phases.closingEntriesPosted) {
                this.completeChecklistItem(closingTask, 5);
                completed++;
            }

            // Update task progress
            closingTask.progress = Math.round((completed / total) * 100);

            // Update status
            if (progress.status === 'completed') {
                closingTask.status = 'completed';
                closingTask.completedAt = new Date().toISOString();
                closingTask.progress = 100;
            } else if (progress.overallProgress > 0) {
                closingTask.status = 'in_progress';
            }

            closingTask.updatedAt = new Date().toISOString();
        }
    }

    private completeChecklistItem(task: AccountingTask, index: number): void {
        if (task.checklist[index] && !task.checklist[index].completed) {
            task.checklist[index].completed = true;
            task.checklist[index].completedAt = new Date().toISOString();
            task.checklist[index].completedBy = 'system';
        }
    }

    // ==========================================================================
    // HELPER METHODS
    // ==========================================================================

    private determinePriority(document: DocumentRecord): TaskPriority {
        if (!document.ai_data) return 'medium';

        // High priority if has audit flags
        if (document.ai_data.audit_flags?.some(f => f.severity === 'high')) {
            return 'high';
        }

        // Low priority if high confidence
        if (document.ai_data.confidence_score >= 90) {
            return 'low';
        }

        return 'medium';
    }

    private calculateDueDate(daysFromNow: number): string {
        const date = new Date();
        date.setDate(date.getDate() + daysFromNow);
        return date.toISOString().slice(0, 10);
    }

    private getEndOfMonth(period: string): string {
        const [year, month] = period.split('-').map(Number);
        const lastDay = new Date(year, month, 0).getDate();
        return `${period}-${lastDay.toString().padStart(2, '0')}`;
    }

    private getEndOfNextMonth(period: string): string {
        const [year, month] = period.split('-').map(Number);
        const nextMonth = month === 12 ? 1 : month + 1;
        const nextYear = month === 12 ? year + 1 : year;
        const lastDay = new Date(nextYear, nextMonth, 0).getDate();
        return `${nextYear}-${nextMonth.toString().padStart(2, '0')}-${lastDay.toString().padStart(2, '0')}`;
    }

    private logEvent(type: TaskSyncEvent['type'], payload: any): void {
        this.eventLog.push({
            type,
            payload,
            timestamp: new Date().toISOString()
        });
    }

    // ==========================================================================
    // PUBLIC API
    // ==========================================================================

    /**
     * Get all tasks
     */
    getTasks(): AccountingTask[] {
        return this.tasks;
    }

    /**
     * Get tasks by client
     */
    getTasksByClient(clientId: string): AccountingTask[] {
        return this.tasks.filter(t => t.accountingContext.clientId === clientId);
    }

    /**
     * Get tasks by period
     */
    getTasksByPeriod(period: string): AccountingTask[] {
        return this.tasks.filter(t => t.accountingContext.period === period);
    }

    /**
     * Get overdue tasks
     */
    getOverdueTasks(): AccountingTask[] {
        const now = new Date();
        return this.tasks.filter(t =>
            t.dueDate &&
            new Date(t.dueDate) < now &&
            !['completed', 'cancelled'].includes(t.status)
        );
    }

    /**
     * Get upcoming deadlines (next 7 days)
     */
    getUpcomingDeadlines(days: number = 7): AccountingTask[] {
        const now = new Date();
        const future = new Date();
        future.setDate(future.getDate() + days);

        return this.tasks.filter(t =>
            t.dueDate &&
            new Date(t.dueDate) >= now &&
            new Date(t.dueDate) <= future &&
            !['completed', 'cancelled'].includes(t.status)
        );
    }

    /**
     * Get event log
     */
    getEventLog(): TaskSyncEvent[] {
        return this.eventLog;
    }
}

// Export singleton
export const accountingTaskSync = new AccountingTaskSyncService();

export default accountingTaskSync;
